apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-service
  labels:
    app: {{ .Values.container.name }}
spec:
  ports:
  - port: {{ .Values.container.port }}
    protocol: TCP
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.container.name }}
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.container.name }}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.container.static_ip_name }}
    networking.gke.io/managed-certificates: {{ .Values.container.name }}-certificate
spec:
  backend:
    serviceName: {{ .Values.container.name }}-service
    servicePort: {{ .Values.container.port }}
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ .Values.container.name }}-certificate
spec:
  domains:
    - {{ .Values.container.domain }}
